name: Post on TikTok

on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v4

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 20.x

      - name: Install Dependencies and Linting
        run: pnpm install && pnpm lint

      - name: Initialize Chrome
        run: pnpm remotion:chrome

      - name: Render video.mp4
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        # run: node scripts/generate-props && pnpm remotion:render -- --props="./input-props.json"
        run: pnpm remotion:render
