name: Upload to TikTok inbox

on:
  workflow_dispatch:
  schedule:
    # Runs at 21:00 (09:00 PM) UTC every day
    - cron: '0 21 * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    environment:
      name: TikTok
      url: https://www.tiktok.com/@holy.quran.clips

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v4

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20.x

      - name: Install Dependencies and Linting
        run: pnpm install && pnpm lint

      - name: Initialize Chrome
        run: pnpm remotion:chrome

      - name: Render video.mp4
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          RUN_COUNT: ${{ github.run_number }}
        run: |
          node scripts/download-assets.js
          pnpm remotion:render

      - name: Upload to TikTok
        run: pnpm upload
        env:
          TIKTOK_CLIENT_KEY: ${{ secrets.TIKTOK_CLIENT_KEY }}
          TIKTOK_CLIENT_SECRET: ${{ secrets.TIKTOK_CLIENT_SECRET }}
          TIKTOK_REFRESH_TOKEN: ${{ secrets.TIKTOK_REFRESH_TOKEN }}
